set number
set numberwidth=1
set clipboard=unnamed
syntax enable
set showcmd
set encoding=utf-8
set showmatch
set sw=2
set laststatus=2
set showmode
set tabstop=2
set shiftwidth=4
set expandtab
set cursorcolumn 
set cursorline
hi CursorLine cterm=NONE ctermbg=red ctermfg=white
hi CursorColumn cterm=NONE ctermbg=red ctermfg=white
nnoremap H :set cursorline! cursorcolumn!

